server:
  port: 8080

piper:
  url: ${PIPER_URL}

telegram:
  bot:
    token: ${TELEGRAM_BOT_TOKEN}
    name: "radix-bot"

spring:
  datasource:
    url: ${POSTGRESQL_DB_URL}
    username: ${POSTGRESQL_DB_USER}
    password: ${POSTGRESQL_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

groq:
  api-key: ${GROQ_API_KEY}
  base-url: https://api.groq.com/openai/v1
  model: openai/gpt-oss-20b

anki:
  baseUrl: ${ANKI_BASE_URL}